import { Sale, ConsortiumType, SaleStatus } from '../types';
import { supabase } from './supabase';

// Map database columns (snake_case) to application types (camelCase)
const mapFromDb = (row: any): Sale => ({
  id: row.id,
  consultantName: row.consultant_name,
  clientName: row.client_name,
  type: row.type as ConsortiumType,
  value: Number(row.value),
  date: row.date,
  status: row.status as SaleStatus,
});

const mapToDb = (sale: Sale) => ({
  // id is auto-generated by Supabase if not provided, but we might pass it if needed
  consultant_name: sale.consultantName,
  client_name: sale.clientName,
  type: sale.type,
  value: sale.value,
  date: sale.date,
  status: sale.status,
});

export const getSales = async (): Promise<Sale[]> => {
  const { data, error } = await supabase
    .from('sales')
    .select('*')
    .order('date', { ascending: false });

  if (error) {
    console.error('Error fetching sales:', error);
    return [];
  }

  return (data || []).map(mapFromDb);
};

export const saveSales = async (sales: Sale[]): Promise<void> => {
  // This function is now used for bulk import
  const dbRows = sales.map(mapToDb);
  
  const { error } = await supabase
    .from('sales')
    .insert(dbRows);

  if (error) {
    console.error('Error bulk saving sales:', error);
    throw error;
  }
};

export const addSale = async (sale: Sale): Promise<void> => {
  const dbRow = mapToDb(sale);
  
  const { error } = await supabase
    .from('sales')
    .insert([dbRow]);

  if (error) {
    console.error('Error adding sale:', error);
    throw error;
  }
};

export const generateMockData = async (): Promise<Sale[]> => {
  const mockSales: Sale[] = [
    { id: '1', consultantName: 'Ana Silva', clientName: 'Transportadora Veloz', type: ConsortiumType.HEAVY_MACHINERY, value: 450000, date: '2024-05-10', status: SaleStatus.APPROVED },
    { id: '2', consultantName: 'Carlos Souza', clientName: 'João Ferreira', type: ConsortiumType.AUTO, value: 80000, date: '2024-05-12', status: SaleStatus.APPROVED },
    { id: '3', consultantName: 'Ana Silva', clientName: 'Maria Helena', type: ConsortiumType.REAL_ESTATE, value: 300000, date: '2024-05-15', status: SaleStatus.PENDING },
    { id: '4', consultantName: 'Roberto Dias', clientName: 'Tech Solutions', type: ConsortiumType.SERVICES, value: 20000, date: '2024-05-18', status: SaleStatus.APPROVED },
    { id: '5', consultantName: 'Carlos Souza', clientName: 'Pedro Alencar', type: ConsortiumType.MOTORCYCLE, value: 25000, date: '2024-05-20', status: SaleStatus.APPROVED },
    { id: '6', consultantName: 'Ana Silva', clientName: 'Fazenda Esperança', type: ConsortiumType.HEAVY_MACHINERY, value: 600000, date: '2024-05-22', status: SaleStatus.APPROVED },
    { id: '7', consultantName: 'Roberto Dias', clientName: 'Clínica Sorriso', type: ConsortiumType.REAL_ESTATE, value: 500000, date: '2024-05-25', status: SaleStatus.PENDING },
    { id: '8', consultantName: 'Ana Silva', clientName: 'Lucas Torres', type: ConsortiumType.AUTO, value: 120000, date: '2024-05-28', status: SaleStatus.APPROVED },
  ];
  
  // Clean format for DB
  const dbRows = mockSales.map(mapToDb);

  const { error } = await supabase.from('sales').insert(dbRows);
  
  if (error) {
    console.error("Error generating mock data", error);
    return [];
  }
  
  return mockSales;
};