import React, { useState, useEffect } from 'react';
import { ConsortiumType, Sale, SaleStatus } from '../types';
import { v4 as uuidv4 } from 'uuid';
import { PlusCircle, Save, Share2, Check, Loader2, Copy } from 'lucide-react';

interface SalesEntryProps {
  onAddSale: (sale: Sale) => Promise<void>;
  isStandalone?: boolean;
}

export const SalesEntry: React.FC<SalesEntryProps> = ({ onAddSale, isStandalone = false }) => {
  const [formData, setFormData] = useState({
    consultantName: '',
    clientName: '',
    type: ConsortiumType.AUTO,
    value: '',
    date: new Date().toISOString().split('T')[0],
    status: SaleStatus.PENDING
  });

  const [copied, setCopied] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [shareUrl, setShareUrl] = useState('');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const url = `${window.location.origin}${window.location.pathname}?mode=consultant`;
      setShareUrl(url);
    }
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.consultantName || !formData.clientName || !formData.value) return;

    setIsSubmitting(true);

    const newSale: Sale = {
      // ID will be generated by Supabase if we don't send it, but we can generate UUID for local optimism if needed.
      // However, onAddSale is mapped to send to DB.
      id: uuidv4(),
      consultantName: formData.consultantName,
      clientName: formData.clientName,
      type: formData.type,
      value: parseFloat(formData.value),
      date: formData.date,
      status: formData.status
    };

    try {
      await onAddSale(newSale);
      
      // Reset form on success
      setFormData({
        ...formData,
        clientName: '',
        value: '',
        status: SaleStatus.PENDING
      });
    } catch (error) {
      console.error(error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={`max-w-2xl mx-auto bg-white rounded-xl shadow-sm border border-gray-200 p-8 animate-fade-in ${isStandalone ? 'w-full' : ''}`}>
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-6 border-b border-gray-100 pb-4 gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-red-50 rounded-lg text-[#D31145]">
            <PlusCircle size={24} />
          </div>
          <div>
            <h2 className="text-xl font-bold text-[#003057]">Registrar Nova Venda</h2>
            <p className="text-sm text-gray-500">Insira os detalhes do contrato.</p>
          </div>
        </div>
        
        {!isStandalone && (
          <div className="flex items-center gap-2 bg-gray-50 p-1.5 rounded-lg border border-gray-200 w-full md:w-auto">
            <div className="text-xs text-gray-500 px-2 truncate max-w-[150px] md:max-w-[200px]" title={shareUrl}>
              {shareUrl}
            </div>
            <button 
              onClick={handleCopyLink}
              className="flex items-center gap-2 px-3 py-1.5 bg-white hover:bg-gray-100 text-[#003057] rounded-md text-xs font-medium transition border border-gray-200 shadow-sm shrink-0"
              title="Copiar link para enviar aos consultores"
            >
              {copied ? <Check size={14} className="text-green-600" /> : <Copy size={14} />}
              {copied ? 'Copiado!' : 'Copiar Link'}
            </button>
          </div>
        )}
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* Consultant Name */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Nome do Consultor</label>
            <input
              type="text"
              name="consultantName"
              value={formData.consultantName}
              onChange={handleChange}
              disabled={isSubmitting}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D31145] focus:border-[#D31145] outline-none transition disabled:bg-gray-100"
              placeholder="Ex: João Silva"
              required
            />
          </div>

          {/* Client Name */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Nome do Cliente</label>
            <input
              type="text"
              name="clientName"
              value={formData.clientName}
              onChange={handleChange}
              disabled={isSubmitting}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D31145] focus:border-[#D31145] outline-none transition disabled:bg-gray-100"
              placeholder="Ex: Transportadora XYZ"
              required
            />
          </div>

          {/* Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Tipo de Bem</label>
            <select
              name="type"
              value={formData.type}
              onChange={handleChange}
              disabled={isSubmitting}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D31145] focus:border-[#D31145] outline-none transition disabled:bg-gray-100"
            >
              {Object.values(ConsortiumType).map((type) => (
                <option key={type} value={type}>{type}</option>
              ))}
            </select>
          </div>

          {/* Value */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Valor do Crédito (R$)</label>
            <input
              type="number"
              name="value"
              value={formData.value}
              onChange={handleChange}
              disabled={isSubmitting}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D31145] focus:border-[#D31145] outline-none transition disabled:bg-gray-100"
              placeholder="0.00"
              min="0"
              step="0.01"
              required
            />
          </div>

           {/* Date */}
           <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Data da Venda</label>
            <input
              type="date"
              name="date"
              value={formData.date}
              onChange={handleChange}
              disabled={isSubmitting}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D31145] focus:border-[#D31145] outline-none transition disabled:bg-gray-100"
              required
            />
          </div>

          {/* Status */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Status Inicial</label>
            <select
              name="status"
              value={formData.status}
              onChange={handleChange}
              disabled={isSubmitting}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#D31145] focus:border-[#D31145] outline-none transition disabled:bg-gray-100"
            >
              {Object.values(SaleStatus).map((status) => (
                <option key={status} value={status}>{status}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="pt-4">
          <button
            type="submit"
            disabled={isSubmitting}
            className="w-full bg-[#D31145] hover:bg-[#b00e3a] text-white font-bold py-3 px-6 rounded-lg flex items-center justify-center gap-2 transition duration-200 shadow-md hover:shadow-lg uppercase tracking-wide text-sm disabled:opacity-70 disabled:cursor-not-allowed"
          >
            {isSubmitting ? <Loader2 className="animate-spin" size={20} /> : <Save size={20} />}
            {isSubmitting ? 'Salvando...' : 'Salvar Venda'}
          </button>
        </div>
      </form>
    </div>
  );
};